version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: container_rabbitmq
    restart: always
    ports:
     - 15672:15672
     - 5672:5672
     - 25676:25676
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - default_network

  mongo:
    container_name: container-mongo
    image: mongo:3
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
    - default_network

  people_service:
    image: node:16-alpine
    container_name: container_people_service
    working_dir: /usr/app
    restart: on-failure
    command: sh -c "npm run build && npm start"
    ports:
     - 3333:3333
    environment:
      MONGO_URL: mongodb://mongo/people
      RABBIT_MQ_URL: amqp://admin:admin@rabbitmq
    volumes:
      - ./people:/usr/app
    links:
      - mongo
      - rabbitmq
    depends_on:
        - rabbitmq
        - mongo
    networks:
      - default_network
  
  nginx:
    image: nginx:1
    container_name: container_lb
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default_network
    depends_on:
        - rabbitmq
        - mongo
        - people_service
    links:
      - rabbitmq
      - mongo
      - people_service

networks:
  default_network:
    driver: bridge

volumes:
  rabbitmq_data:
  mongo_data:
